
############################################
##### Config worker gosbench ###############
############################################
worker:
  - name: worker1
  - name: worker2
  - name: worker3
  - name: worker4
###########################################
#### Config gosbench ######################
###########################################
s3_config:
  access_key: 
  secret_key: 
  region: cy-store
  endpoint: https://rgw.cyuucloud.xyz
  skipSSLverify: false
grafana_config:
  endpoint: http://10.10.1.1:3000
  username: cyyoon
  password:
tests:
  name: EverythingWorks
  read_weight: 20
  write_weight: 80
  delete_weight: 30
  list_weight: 10
  objects:
    size_min: 5
    size_max: 1000
    part_size: 0
    size_distribution: random
    unit: KB
    number_min: 100
    number_max: 100
    number_distribution: constant
  buckets:
    number_min: 1
    number_max: 10
    number_distribution: constant
  bucket_prefix: cy-gosbench1-
  object_prefix: obj
  stop_with_runtime:
  stop_with_ops: 3000
  workers: 4
  workers_share_buckets: True
  parallel_clients: 3
  clean_after: true

###########################################
#### Config gosbench server ###############
###########################################
server:
  image:
    registry: quay.io
    repository: mulbc/gosbench-server
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 2000
    targetPort: 2000
    nodePort: 32000
    selector:
      app: gosbench-server
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

