############################################
##### Config worker job gosbench ###########
############################################
worker_job:
  - name: worker1
    nodeselector: job1
    port: "8888"
  - name: worker2
    port: "8889"
    nodeselector: job1
  - name: worker3
    nodeselector: job2
    port: "8888"
  - name: worker4
    nodeselector: job2
    port: "8889"

############################################
##### Config worker gosbench ###############
############################################
worker:
  name: worker      
  image:
    registry: quay.io
    repository: mulbc/gosbench-worker
    tag: latest
    pullPolicy: IfNotPresent
 
###########################################
#### Config gosbench ######################
###########################################
gosbench_config: 
  name: gosbench-config
  s3:
    access_key: 
    secret_key: 
    region: cy-store
    endpoint: https://rgw.cyuucloud.xyz
    skipSSLverify: false
  grafana:
    endpoint: http://10.10.1.1:3000
    username: cyyoon
    password:
  tests:
    name: EverythingWorks
    read_weight: 20
    write_weight: 80
    delete_weight: 30
    list_weight: 10
    objects:
      size_min: 5
      size_max: 1000
      part_size: 0
      size_distribution: random
      unit: KB
      number_min: 100
      number_max: 100
      number_distribution: constant
    buckets:
      number_min: 1
      number_max: 10
      number_distribution: constant
    bucket_prefix: cy-gosbench1-
    object_prefix: obj
    stop_with_runtime:
    stop_with_ops: 3000
    workers_share_buckets: True
    parallel_clients: 3
    clean_after: true
    workers: 4

###########################################
#### Config gosbench server ###############
###########################################
server:
  name: server 
  container:
    port: 2000
    config_path: /app/config
  image:
    registry: quay.io
    repository: mulbc/gosbench-server
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    nodePort: 32000
    selector:
      app: gosbench-server
  endpoint: 10.10.2.15
