---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.gosbench_config.name }}
  labels:
    app: gosbench-config
data:
  config.yml: |-
    s3_config:
      - access_key: {{ .Values.gosbench_config.s3.access_key }}
        secret_key: {{ .Values.gosbench_config.s3.secret_key }}
        region: {{ .Values.gosbench_config.s3.region }}
        endpoint: {{ .Values.gosbench_config.s3.endpoint }}
        skipSSLverify: {{ .Values.gosbench_config.s3.skipSSLverify }}
    grafana_config:
      endpoint: {{ .Values.gosbench_config.grafana.endpoint }}
      username: {{ .Values.gosbench_config.grafana.username }}
      password: {{ .Values.gosbench_config.grafana.password }}
    tests:
      - name: {{ .Values.gosbench_config.tests.name }}
        read_weight: {{ .Values.gosbench_config.tests.read_weight }}
        write_weight: {{ .Values.gosbench_config.tests.write_weight }}
        delete_weight: {{ .Values.gosbench_config.tests.delete_weight }}
        list_weight: {{ .Values.gosbench_config.tests.list_weight }}
        objects:
          size_min: {{ .Values.gosbench_config.tests.objects.size_min }}
          size_max: {{ .Values.gosbench_config.tests.objects.size_max }}
          part_size: {{ .Values.gosbench_config.tests.objects.part_size }}
          size_distribution: {{ .Values.gosbench_config.tests.objects.size_distribution }}
          unit: {{ .Values.gosbench_config.tests.objects.unit }}
          number_min: {{ .Values.gosbench_config.tests.objects.number_min }}
          number_max: {{ .Values.gosbench_config.tests.objects.number_max }}
          number_distribution: {{ .Values.gosbench_config.tests.objects.number_distribution }}
        buckets:
          number_min: {{ .Values.gosbench_config.tests.buckets.number_min }}
          number_max: {{ .Values.gosbench_config.tests.buckets.number_max }}
          number_distribution: {{ .Values.gosbench_config.tests.buckets.number_distribution }}
        bucket_prefix: {{ .Values.gosbench_config.tests.bucket_prefix }}
        object_prefix: {{ .Values.gosbench_config.tests.object_prefix }}
        stop_with_runtime: {{ .Values.gosbench_config.tests.stop_with_runtime }}
        stop_with_ops: {{ .Values.gosbench_config.tests.stop_with_ops }}
        workers: {{ .Values.gosbench_config.tests.workers }}
        workers_share_buckets: {{ .Values.gosbench_config.tests.workers_share_buckets }}
        parallel_clients: {{ .Values.gosbench_config.tests.parallel_clients }}
        clean_after: {{ .Values.gosbench_config.tests.clean_after }}
