---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gosbench.fullname" . }}-server
  labels:
    app: gosbench-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gosbench-server
  template:
    metadata:
      labels:
        app: gosbench-server
    spec:
      containers:
        - name: server
          image: "{{ .Values.server.image.registry }}/{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          command: ['./main', '-p', '{{ .Values.server.container.port }}', '-d', '-c', '{{ .Values.server.container.config_path }}/config.yml']
          ports:
            - containerPort: {{ .Values.server.container.port }}
          volumeMounts:
            - name: {{ .Values.gosbench_config.name }}
              mountPath: {{ .Values.server.container.config_path }}
      volumes:
        - name: {{ .Values.gosbench_config.name }}
          configMap:
            name: {{ .Values.gosbench_config.name }}
