{{- range $worker := .Values.worker }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $worker.name }}
  labels:
    app: gosbench-worker
    stack: gosbench
    type: worker
spec:
  template:
    metadata:
      labels:
        app: gosbench-worker
        stack: gosbench
        type: worker
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: type
                  operator: In
                  values:
                  - worker
              topologyKey: kubernetes.io/hostname
      containers:
        - name: gosbench-worker
          image: quay.io/mulbc/gosbench-worker:latest
          imagePullPolicy: Always
          #command: ['./main', '-s', 'gosbench-server:2000']
          command: ['./main', '-s', '10.10.1.14:32000']
          ports:
            - containerPort: 8888
      hostNetwork: true
      restartPolicy: Never

---
{{- end }}
