{{- $root := . -}} 
{{ range $worker := .Values.worker_job }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $worker.name }}
  labels:
    app: gosbench-worker
spec:
  template:
    metadata:
      labels:
        app: gosbench-worker
    spec:
      nodeSelector:
        worker: {{ $worker.nodeselector }}
      containers:
        - name: {{ $worker.name }}
          image: "{{ $root.Values.worker.image.registry }}/{{ $root.Values.worker.image.repository }}:{{ $root.Values.worker.image.tag }}"
          imagePullPolicy: {{ $root.Values.worker.image.pullPolicy }}
          command: ['./main', '-s', '{{ $root.Values.server.endpoint }}:{{ $root.Values.server.service.nodePort }}' , '-p', '{{ $worker.port }}']
          ports:
            - containerPort: {{ $worker.port }}
      hostNetwork: true
      restartPolicy: Never
---
{{- end }}
