apiVersion: v1
kind: Service
metadata:
  name: {{ include "gosbench.fullname" . }}-server
  labels:
    {{- include "gosbench.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.container.port }}
      targetPort: {{ .Values.server.container.targetPort }}
      nodePort: {{ .Values.server.service.nodePort }}
  selector:
    {{- include "gosbench.server.selectorLabels" . | nindent 4 }}
